language: java
jdk:
    -openjdk8

addons:
    sonarcloud:
        organization: giuseppelasco
        token: 4343157045eb41f6a4cd5066cfe18ab7b2721ae9
script:
    -ant build
    -sonar-scanner