language: java
jdk:
    - openjdk8

addons:
    sonarcloud:
        organization: giuseppelasco17
        token: 711cb280b4d60652dceabfcda04f11230733c46d
script:
    - ant build
    - sonar-scanner